name: PPCOC Test Site
favicon: null
layout_spectrum: 0.5025834676343948
typography_spectrum: 0.8443384352140129
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5791814790572971
  lightness: 0.5523862256668508
  saturation: 0.8637816754635423
  rhythmicContrast: 0.8146531500387937
purpose: []
